# ---------- build stage ----------
FROM maven:3.9.4-eclipse-temurin-17 AS build
WORKDIR /workspace

# copy maven files and source
COPY pom.xml .
COPY src ./src

# build jar (skip tests to be faster)
RUN mvn -B -DskipTests package

# ---------- runtime stage ----------
FROM openjdk:17-slim
WORKDIR /app

# copy jar from build stage
COPY --from=build /workspace/target/*.jar app.jar

EXPOSE 8081
ENTRYPOINT ["java","-jar","/app/app.jar"]
